import tkinter as tk
from tkinter import messagebox
import smtplib
from email.message import EmailMessage

# ==========================================
# GMAIL CONFIGURATION
# ==========================================

SENDER_EMAIL = "lifesaverai28@gmail.com"
APP_PASSWORD = "wabczfagrddckbfm"

# ==========================================
# SEND ALERT FUNCTION
# ==========================================

def send_alert():

    receiver_email = email_entry.get().strip()
    mobile1 = mobile1_entry.get().strip()
    mobile2 = mobile2_entry.get().strip()
    emergency_msg = message_box.get("1.0", tk.END).strip()

    if receiver_email == "":
        messagebox.showerror(
            "Error",
            "Please enter an email address."
        )
        return

    try:

        msg = EmailMessage()

        msg["Subject"] = "🚨 Emergency Alert - Life Saver AI"
        msg["From"] = SENDER_EMAIL
        msg["To"] = receiver_email

        msg.set_content(f"""
🚨 EMERGENCY ALERT 🚨

Mobile Number 1:
{mobile1}

Mobile Number 2:
{mobile2}

Emergency Message:
{emergency_msg}

Generated by Life Saver AI
""")

        server = smtplib.SMTP(
            "smtp.gmail.com",
            587
        )

        server.starttls()

        server.login(
            SENDER_EMAIL,
            APP_PASSWORD
        )

        server.send_message(msg)

        server.quit()

        messagebox.showinfo(
            "Life Saver AI",
            "🚨 Emergency Alert Sent Successfully!"
        )

        # Clear all fields after sending
        email_entry.delete(0, tk.END)
        mobile1_entry.delete(0, tk.END)
        mobile2_entry.delete(0, tk.END)
        message_box.delete("1.0", tk.END)

    except Exception as e:

        messagebox.showerror(
            "Email Error",
            str(e)
        )

# ==========================================
# MAIN WINDOW
# ==========================================

root = tk.Tk()

root.title("Life Saver AI")
root.geometry("600x650")
root.resizable(False, False)
root.configure(bg="#0F172A")

# ==========================================
# TITLE
# ==========================================

title = tk.Label(
    root,
    text="🚨 Life Saver AI",
    font=("Segoe UI", 22, "bold"),
    bg="#0F172A",
    fg="white"
)
title.pack(pady=(15, 5))

subtitle = tk.Label(
    root,
    text="Emergency Alert System",
    font=("Segoe UI", 10),
    bg="#0F172A",
    fg="#CBD5E1"
)
subtitle.pack()

# ==========================================
# CARD FRAME
# ==========================================

card = tk.Frame(
    root,
    bg="#1E293B",
    padx=20,
    pady=20
)

card.pack(
    padx=20,
    pady=20,
    fill="both",
    expand=True
)

# ==========================================
# EMAIL ADDRESS
# ==========================================

tk.Label(
    card,
    text="📧 Email Address",
    font=("Segoe UI", 10, "bold"),
    bg="#1E293B",
    fg="white"
).pack(anchor="w")

email_entry = tk.Entry(
    card,
    font=("Segoe UI", 11),
    bg="#F8FAFC",
    width=45
)

email_entry.pack(
    pady=6,
    ipady=5
)

# ==========================================
# MOBILE NUMBER 1
# ==========================================

tk.Label(
    card,
    text="📱 Mobile Number 1",
    font=("Segoe UI", 10, "bold"),
    bg="#1E293B",
    fg="white"
).pack(anchor="w")

mobile1_entry = tk.Entry(
    card,
    font=("Segoe UI", 11),
    bg="#F8FAFC",
    width=45
)

mobile1_entry.pack(
    pady=6,
    ipady=5
)

# ==========================================
# MOBILE NUMBER 2
# ==========================================

tk.Label(
    card,
    text="📱 Mobile Number 2",
    font=("Segoe UI", 10, "bold"),
    bg="#1E293B",
    fg="white"
).pack(anchor="w")

mobile2_entry = tk.Entry(
    card,
    font=("Segoe UI", 11),
    bg="#F8FAFC",
    width=45
)

mobile2_entry.pack(
    pady=6,
    ipady=5
)

# ==========================================
# MESSAGE BOX
# ==========================================

tk.Label(
    card,
    text="📝 Emergency Message",
    font=("Segoe UI", 10, "bold"),
    bg="#1E293B",
    fg="white"
).pack(anchor="w")

message_box = tk.Text(
    card,
    height=5,
    width=45,
    font=("Segoe UI", 11),
    bg="#F8FAFC"
)

message_box.pack(
    pady=8
)

# ==========================================
# SEND BUTTON
# ==========================================

send_btn = tk.Button(
    card,
    text="SEND ALERT",
    command=send_alert,
    bg="#DC2626",
    fg="white",
    font=("Arial", 12, "bold"),
    width=20,
    height=2
)

send_btn.pack(pady=15)

send_btn.pack(pady=15)

# ==========================================
# FOOTER
# ==========================================

footer = tk.Label(
    root,
    text="Life Saver AI © Hackathon Project",
    font=("Segoe UI", 9),
    bg="#0F172A",
    fg="#94A3B8"
)

footer.pack(pady=5)

# ==========================================
# RUN APPLICATION
# ==========================================

root.mainloop()